server:
  port: 9901
  servlet:
    context-path: /auth

spring:
  application:
    # 应用名称
    name: page-auth
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  devtools:
    livereload:
      port: 35729
  # mysql数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/pagedb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  # redis
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ''
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

# mybatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapping/**/*Mapper.xml
  type-aliases-package: com.jias.page.domain
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1

# 是否开启加密传输模式
net-transfer:
  #  请求加密
  request-safe: false
  #  响应加密
  response-safe: false
  # 默认AES的key
  aes-key: def009A1bcO538JK


logging:
  file:
    path: logs/auth
  level:
    com.jias.page: debug


